apiVersion: v1
kind: Service
metadata:
  name: plugnmeet-recorder-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000  
      targetPort: 4000
      name: tcp
      nodePort: 31491
  selector:
    app: plugnmeet-recorder